<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Zend Framework Project</title>
      <?php 
	  	echo $this->headLink()->prependStylesheet($this->baseUrl('/public/styles/global.css'));
      	echo $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js');
      ?>
      
    </head>
    <body>
	    <div id="header">
	        <div id="header-logo">
	            <h2><b>Zend Framework project</b></h2>
	        </div>
	    </div>
     	
     	<div id="content"> 
    		<?php echo $this->layout()->content ?>
    	</div>
     
    </body>
</html>