<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Zend Framework Project</title>
      <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
    </head>
    <body>
	    <div id="header">
	        <div id="header-logo">
	            <b>Zend Framework project</b>
	        </div>
	        
	    </div>
     
    	<?php echo $this->layout()->content ?>
     
    </body>
</html>